# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bccce23becb3b2e2fe5489ac2ff69179e1e2324afa5bb6233578ac720d9f5c635fd8df2b29177455a7e16d896c5e9cba482e755e86d3b581c177558ad4853085

test:
  secret_key_base: e59afe4f91d251218853c77a45903a675744c0f350d4ab2fd1642a2ae684bcc5c199d7302f3bb50cb5a780692c1272244cff5eea60272962addb14253411b726

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
